name: webtv_app
description: Netflix-style VOD app for WebTV Solutions CMS
publish_to: 'none'
version: 2.0.9+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  dio: ^5.4.0
  crypto: ^3.0.3
  cached_network_image: ^3.3.0
  video_player: ^2.8.1
  chewie: ^1.7.4
  shimmer: ^3.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

dependency_overrides:
  package_info_plus: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
